-- M8 trip execution gates + location samples

ALTER TABLE "Trip" ADD COLUMN IF NOT EXISTS "safetyPassedAt" TIMESTAMP(3);
ALTER TABLE "Trip" ADD COLUMN IF NOT EXISTS "safetyFailedAt" TIMESTAMP(3);
ALTER TABLE "Trip" ADD COLUMN IF NOT EXISTS "safetyNotes" TEXT;
ALTER TABLE "Trip" ADD COLUMN IF NOT EXISTS "declaredMassKg" DOUBLE PRECISION;
ALTER TABLE "Trip" ADD COLUMN IF NOT EXISTS "actualMassKg" DOUBLE PRECISION;
ALTER TABLE "Trip" ADD COLUMN IF NOT EXISTS "massCheckOk" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Trip" ADD COLUMN IF NOT EXISTS "massCheckedAt" TIMESTAMP(3);
ALTER TABLE "Trip" ADD COLUMN IF NOT EXISTS "massOverDeclared" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Trip" ADD COLUMN IF NOT EXISTS "onBreak" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Trip" ADD COLUMN IF NOT EXISTS "breakStartedAt" TIMESTAMP(3);

CREATE TABLE IF NOT EXISTS "TripLocationSample" (
  "id" TEXT NOT NULL,
  "tripId" TEXT NOT NULL,
  "lat" DECIMAL(10,7) NOT NULL,
  "lng" DECIMAL(10,7) NOT NULL,
  "recordedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "TripLocationSample_pkey" PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "TripLocationSample_tripId_recordedAt_idx" ON "TripLocationSample"("tripId", "recordedAt");

DO $$ BEGIN
  ALTER TABLE "TripLocationSample" ADD CONSTRAINT "TripLocationSample_tripId_fkey"
    FOREIGN KEY ("tripId") REFERENCES "Trip"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
