export const homeCopyEn = {
  nav: [
    ['Home', '#banner'],
    ['About', '#aboutus'],
    ['Compare', '#comparison'],
    ['Features', '#features'],
    ['Journey', '#process'],
    ['Ecosystem', '#ecosystem'],
    ['FAQ', '#faq'],
  ],
  announceBar: 'Pre-launch site — marketplace coming soon. Register early for priority access.',
  tagline: 'Australia’s Digital Full-Load Freight Marketplace',
  slide1TitleLead: "Australia's Digital Full-Load",
  slide1TitleAccent: 'Freight Marketplace',
  slide1Body:
    'CLOX is a pre-launch digital marketplace connecting corporate senders with vetted heavy-vehicle operators and transport fleets — built for transparent bidding, visibility, and protected payments.',
  slide2TitleLead: 'Move Your Goods',
  slide2TitleAccent: 'Quickly & Securely',
  slide2Body:
    'Smart freight forwarding made simple, transparent, and efficient. No more complicated forms or endless phone calls to chase down quotes—just the essentials you need to move your goods quickly, affordably, and securely.',
  slide3TitleLead: 'Freight Without',
  slide3TitleAccent: 'the Friction',
  slide3Body:
    'A connected freight experience designed to reduce manual handoffs, improve visibility, and help Australian senders and transport operators move with confidence.',
  slide4TitleLead: 'One Connected',
  slide4TitleAccent: 'Freight Ecosystem',
  slide4Body:
    'CLOX is being built to bring corporate senders, vetted carriers, transparent bidding, tracking, and protected payments into one streamlined digital journey.',
  explore: 'Explore the Platform',
  sendFreightCta: 'Send Freight',
  joinCarrierCta: 'Join as Carrier',
  preLaunch: 'Join Pre-Launch',
  preLaunchShort: 'Join Pre-Launch',
  overviewEyebrow: 'Transforming Australian Logistics',
  overviewTitle: 'Company Overview',
  overviewBody:
    "Welcome to CLOX — Australia's digital full-load freight marketplace. We are transforming logistics by bringing simplicity, transparency, and visibility to the modern supply chain. By replacing high-overhead manual middleware with a high-efficiency digital ecosystem, CLOX connects corporate senders directly with vetted heavy vehicle operators while securing transactions via planned protected upfront payments.",
  visionTab: 'Our Vision',
  missionTab: 'Our Mission',
  visionBody:
    "CLOX is Australia's smartest freight solution. We replace manual middleware with a digital marketplace, connecting corporate senders directly with vetted heavy vehicle operators via planned protected upfront payments.",
  missionBody:
    'Our mission is to empower shippers and carriers through a digital full-load freight marketplace. We eliminate frictional costs and operational bottlenecks to deliver fast, automated, and clearer logistics.',
  nextTitle: 'The Next Generation of Logistics',
  nextBody:
    'CLOX represents the next generation of digital full-load logistics. By modernizing Australian freight through an automated marketplace, the platform bridges the gap between shippers looking for competitive pricing and carriers looking to optimize asset utilization. Our technology removes traditional frictional costs, returning control, speed, and visibility to the businesses that drive our economy.',
  discover: 'Discover the Ecosystem',
  legacyTitle: 'Legacy Middleware',
  legacySub: 'Slow. Manual. Error-Prone.',
  legacy: [
    'Manual Data Entry',
    'Rate Errors',
    'Slow Response',
    'Limited Visibility',
    'High Operational Cost',
    'Manpower Intensive',
  ],
  legacyStats: [
    'Hours to Quote',
    'High Error Rate',
    'High Operational Cost',
    'Reactive Problem Solving',
    'Manpower Intensive',
  ],
  futureTitle: 'Digital Freight Marketplace',
  futureSub: 'Faster. Automated. Clearer.',
  future: [
    'Real-Time Visibility',
    'Transparent Bidding',
    'Smart Rate Matching',
    'End-to-End Tracking',
    'Lower Costs, Higher Efficiency',
    'Data-Driven Insights',
  ],
  futureStats: [
    'Minutes to Quote',
    'High Accuracy',
    'Lower Costs',
    'Proactive Control & Insights',
    'Scalable Growth',
  ],
  futureFooter: 'The Future of Freight Is Digital',
  joinEcosystem: 'Join the Ecosystem',
  featuresTitle: 'How We Help You Ship Smarter',
  features: [
    [
      'Clear Comparisons',
      'Compare freight providers, delivery times, reliability ratings, and pricing as the marketplace goes live.',
    ],
    [
      'Streamlined Booking',
      'Book shipments digitally in a few seamless clicks once the platform opens.',
    ],
    [
      'Real-Time Tracking',
      'Monitor freight from dispatch to delivery with planned live tracking updates.',
    ],
    [
      'Protected Upfront Payments',
      'Secure payments through planned automated protected upfront payment infrastructure.',
    ],
  ],
  journeyTitle: 'The Digital Shipping Journey',
  journeySub: 'The Simple Four-Step Process',
  steps: [
    [
      'Enter Details',
      'Consignment Posting',
      'Enter freight dimensions, routes, and site-access requirements.',
    ],
    [
      'Compare & Book',
      'Transparent Bidding & Protected Payments',
      'Carriers submit bids, and customer funds are secured before dispatch.',
    ],
    [
      'Move & Track',
      'Real-Time Execution & Tracking',
      'Live GPS tracking with automated route management.',
    ],
    [
      'Deliver',
      'Digital Verification & Carrier Release',
      'After proof of delivery, protected funds are automatically released to the carrier.',
    ],
  ],
  ecosystemEyebrow: 'Dual-Sided Marketplace',
  ecosystemTitle: 'Built for the Entire Ecosystem',
  senderTitle: 'Optimized for Senders',
  senderSub: 'Skip the Middleman Margin. Ship Direct.',
  sender: [
    'Clear Price Comparisons',
    'Live GPS Tracking',
    'Vetted Carrier Compliance',
    'Fewer Futile Trip Disputes',
    'Transparent pricing and terms',
    'Reliable provider evaluations',
    'Better supply chain control',
  ],
  carrierTitle: 'Optimized for Carriers',
  carrierSub: 'Unlock Your Idle Capacity. Reduce Unpaid Freight Risk.',
  carrier: [
    'Protected Upfront Payments',
    'Automated Carrier Payments',
    'Direct Australian Market Access',
    'Maximize Asset Utilization',
    'More steady freight opportunities',
    'Expanded regional network',
    'Funds secured before dispatch',
  ],
  carrierSpotTitle: 'Unlock Your Idle Capacity. Reduce Unpaid Freight Risk.',
  carrierSpotQuestion: 'Tired of Waiting 30 to 60 Days to Get Paid for Your Freight?',
  carrierSpotBody:
    'Welcome to the supply side of the CLOX ecosystem—where dispatch is designed to follow confirmed payment security. CLOX is being built on planned protected upfront payment infrastructure powered by Stripe Connect so customer funds can be secured before loading and released after successful delivery.',
  carrierListTitle: 'Built for Vetted Australian Transport Providers:',
  carrierCards: [
    [
      'Protected Upfront Payout Security',
      'Reduce chasing unpaid or delayed invoices. Funds are designed to be verified before the trip starts.',
    ],
    [
      'Direct Live Job Boards',
      'Bid on regional “Per KM” routes or local “Hourly” blocks (with a planned mandatory 4-hour minimum).',
    ],
    [
      'Direct Marketplace Access',
      'Bid directly on corporate freight proposals matching your precise vehicle type and location.',
    ],
    [
      'Elite Carrier Status',
      'Bidding privileges are reserved for properly vetted operators with valid ABN, Public Liability, and active vehicle compliance.',
    ],
  ],
  verificationTitle: 'Carrier Verification Explained',
  verificationBody:
    'Before live bidding opens, carriers are reviewed for business and vehicle compliance. This is a pre-launch screening process — not a guarantee of admission or ongoing performance.',
  verificationItems: [
    'Valid Australian Business Number (ABN) checks',
    'Public Liability insurance evidence (target $10M–$20M cover)',
    'Active vehicle compliance / Roadworthy Certificates (RWC)',
    'Manual review by State Master Admins before live-bidding privileges',
  ],
  faqTitle: 'Frequently Asked Questions',
  faq: [
    [
      'Is CLOX live today?',
      'No. This is a pre-launch site. You can register interest now; live booking and matching open later.',
    ],
    [
      'How will pricing work?',
      'Senders will post consignments and receive carrier bids. Pricing is competitive and transparent — not a single automated instant quote at launch.',
    ],
    [
      'What does carrier verification cover?',
      'Planned checks include ABN status, Public Liability insurance, and vehicle roadworthiness, with admin review before bidding privileges.',
    ],
    [
      'How are payments protected?',
      'The roadmap uses protected upfront payments so funds can be secured before dispatch and released to the carrier after proof of delivery.',
    ],
    [
      'Does registering create a binding contract?',
      'No. Pre-launch registration and partner EOI are expressions of interest only, subject to formal agreements at go-live.',
    ],
  ],
  zeroDebt: 'BUILT TO REDUCE BAD DEBT RISK.',
  zeroDebtNote:
    '*Our State Master Admins are manually reviewing early registrants to grant live-bidding privileges when the gates open. Have your ABN, insurance details, and RWCs ready.*',
  qrTitle: 'Scan to Secure Payout Priority & Register Free.',
  cohortEyebrow: 'Web & App Platform Coming Soon.',
  cohortTitle: 'Join the Pre-Launch Cohort Today',
  benefitsTitle: 'Early registrants receive:',
  benefits: [
    'Priority booking tiers',
    'Waived platform initiation fees for the first 90 days',
    'Fast-tracked corporate onboarding',
    'Early live-bidding access',
  ],
  iAm: 'I am a...',
  senderCta: 'Sender',
  carrierCta: 'Carrier',
  secureSpot: 'Secure Your Spot',
  partnerCta: 'Partner EOI',
  investorCta: 'Investor Portal',
  privacyShort: 'Privacy',
  termsShort: 'Terms',
  contactShort: 'Contact',
  contactHref: 'mailto:privacy@clox.com.au',
  footerLine: '© 2026 CLOX Freight Forwarding. All rights reserved. | Australia Based',
  footerEntity: 'Achieve Global Enterprises Pty Ltd · Trading as CLOX Freight Forwarding · ABN 48 626 269 387',
  footerTag: 'Australia’s Digital Full-Load Freight Marketplace',
} as const;
