import type { AppLocale } from '@/locales';

export type KnowledgeChunk = {
  id: string;
  locale: AppLocale | 'both';
  title: string;
  path: string;
  text: string;
  tags: string[];
  /** When false, chunk is kept for re-enable but not used by the public site guide. */
  public?: boolean;
};

export const knowledgeChunks: KnowledgeChunk[] = [
  {
    id: 'about-en',
    locale: 'en',
    title: 'What is CLOX?',
    path: '/en',
    tags: ['about', 'product', 'freight', 'australia', 'what', 'clox'],
    text: 'CLOX is Australia’s digital full-load freight marketplace (pre-launch), operated by Achieve Global Enterprises Pty Ltd trading as CLOX Freight Forwarding (ABN 48 626 269 387). It connects corporate senders with vetted heavy-vehicle operators and transport fleets for transparent bidding, visibility, and Protected Upfront Payments. The public site today collects early interest via Registry and Partner EOI — live booking and matching are not open yet.',
  },
  {
    id: 'about-hi',
    locale: 'hi',
    title: 'CLOX क्या है?',
    path: '/hi',
    tags: ['about', 'product', 'freight', 'australia', 'what', 'clox'],
    text: 'CLOX ऑस्ट्रेलिया का डिजिटल फुल-लोड फ्रेट मार्केटप्लेस है (प्री-लॉन्च), जिसे Achieve Global Enterprises Pty Ltd ट्रेडिंग नाम CLOX Freight Forwarding (ABN 48 626 269 387) संचालित करता है। यह कॉर्पोरेट सेंडरों को जाँचे हुए हेवी-व्हीकल ऑपरेटरों और ट्रांसपोर्ट फ़्लीट से जोड़ता है — पारदर्शी बिडिंग, विज़िबिलिटी और Protected Upfront Payments के लिए। आज सार्वजनिक साइट रजिस्ट्री और पार्टनर EOI से शुरुआती रुचि एकत्र करती है; लाइव बुकिंग अभी नहीं खुली है।',
  },
  {
    id: 'about-pa',
    locale: 'pa',
    title: 'CLOX ਕੀ ਹੈ?',
    path: '/pa',
    tags: ['about', 'product', 'freight', 'australia', 'what', 'clox'],
    text: 'CLOX ਆਸਟ੍ਰੇਲੀਆ ਦਾ ਡਿਜੀਟਲ ਫੁੱਲ-ਲੋਡ ਫਰੇਟ ਮਾਰਕੀਟਪਲੇਸ ਹੈ (ਪ੍ਰੀ-ਲਾਂਚ), ਜਿਸ ਨੂੰ Achieve Global Enterprises Pty Ltd ਟ੍ਰੇਡਿੰਗ ਨਾਮ CLOX Freight Forwarding (ABN 48 626 269 387) ਚਲਾਉਂਦਾ ਹੈ। ਇਹ ਕਾਰਪੋਰੇਟ ਸੈਂਡਰਾਂ ਨੂੰ ਜਾਂਚੇ ਹੋਏ ਹੈਵੀ-ਵਹੀਕਲ ਆਪਰੇਟਰਾਂ ਅਤੇ ਟਰਾਂਸਪੋਰਟ ਫਲੀਟਾਂ ਨਾਲ ਜੋੜਦਾ ਹੈ — ਪਾਰਦਰਸ਼ੀ ਬਿਡਿੰਗ, ਵਿਜ਼ੀਬਿਲਿਟੀ ਅਤੇ Protected Upfront Payments ਲਈ। ਅੱਜ ਜਨਤਕ ਸਾਈਟ ਰਜਿਸਟਰੀ ਅਤੇ ਪਾਰਟਨਰ EOI ਰਾਹੀਂ ਸ਼ੁਰੂਆਤੀ ਦਿਲਚਸਪੀ ਇਕੱਠੀ ਕਰਦੀ ਹੈ; ਲਾਈਵ ਬੁਕਿੰਗ ਅਜੇ ਨਹੀਂ ਖੁੱਲ੍ਹੀ।',
  },
  {
    id: 'how-works-en',
    locale: 'en',
    title: 'How CLOX works',
    path: '/en/how-it-works',
    tags: ['how', 'works', 'journey', 'features', 'process', 'bidding', 'tracking', 'payment', 'faq'],
    text: 'Planned digital shipping journey: (1) Sender posts consignment details — dimensions, route, site access. (2) Vetted carriers submit transparent bids; customer funds can be secured with Protected Upfront Payments before dispatch. (3) Move & track with planned live GPS tracking. (4) After proof of delivery, Automated Carrier Payments release funds to the carrier. Vehicle/load matching recommends a minimum vehicle class from shipment details; carriers bid with a compliant vehicle. Features include clear comparisons, streamlined booking (when live), carrier verification (ABN, Public Liability, RWC), real-time tracking, and Protected Upfront Payments. CLOX targets full-load / full-truckload freight — not parcel courier. Launch focus: key Australian corridors (initial Melbourne–Sydney), then expand. Citation pages: /en/how-it-works and /en/faq.',
  },
  {
    id: 'how-works-hi',
    locale: 'hi',
    title: 'CLOX कैसे काम करता है',
    path: '/hi/how-it-works',
    tags: ['how', 'works', 'journey', 'features', 'process', 'bidding', 'tracking', 'payment', 'faq'],
    text: 'योजनाबद्ध डिजिटल शिपिंग यात्रा: (1) सेंडर कंसाइनमेंट विवरण पोस्ट करता है — आयाम, रूट, साइट एक्सेस। (2) जाँचे हुए कैरियर पारदर्शी बिड देते हैं; डिस्पैच से पहले Protected Upfront Payments से फंड सुरक्षित हो सकते हैं। (3) नियोजित लाइव GPS ट्रैकिंग से मूव और ट्रैक। (4) डिलीवरी प्रूफ के बाद Automated Carrier Payments से कैरियर को भुगतान। व्हीकल/लोड मैचिंग न्यूनतम वाहन वर्ग सुझाती है; कैरियर अनुरूप वाहन से बिड करते हैं। सुविधाएँ: तुलना, स्ट्रीमलाइंड बुकिंग (लाइव होने पर), कैरियर सत्यापन (ABN, Public Liability, RWC), ट्रैकिंग, Protected Upfront Payments। फुल-लोड फ्रेट के लिए — पार्सल कूरियर नहीं। लॉन्च फोकस: मुख्य ऑस्ट्रेलियाई कॉरिडोर (शुरुआत Melbourne–Sydney)। उद्धरण पेज: /hi/how-it-works और /hi/faq।',
  },
  {
    id: 'how-works-pa',
    locale: 'pa',
    title: 'CLOX ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ',
    path: '/pa/how-it-works',
    tags: ['how', 'works', 'journey', 'features', 'process', 'bidding', 'tracking', 'payment', 'faq'],
    text: 'ਯੋਜਨਾਬੱਧ ਡਿਜੀਟਲ ਸ਼ਿਪਿੰਗ ਯਾਤਰਾ: (1) ਸੈਂਡਰ ਕੰਸਾਈਨਮੈਂਟ ਵੇਰਵੇ ਪੋਸਟ ਕਰਦਾ ਹੈ — ਆਕਾਰ, ਰੂਟ, ਸਾਈਟ ਐਕਸੈਸ। (2) ਜਾਂਚੇ ਹੋਏ ਕੈਰੀਅਰ ਪਾਰਦਰਸ਼ੀ ਬਿਡ ਦਿੰਦੇ ਹਨ; ਡਿਸਪੈਚ ਤੋਂ ਪਹਿਲਾਂ Protected Upfront Payments ਨਾਲ ਫੰਡ ਸੁਰੱਖਿਅਤ ਹੋ ਸਕਦੇ ਹਨ। (3) ਯੋਜਨਾਬੱਧ ਲਾਈਵ GPS ਟਰੈਕਿੰਗ ਨਾਲ ਮੂਵ ਅਤੇ ਟਰੈਕ। (4) ਡਿਲੀਵਰੀ ਪਰੂਫ ਤੋਂ ਬਾਅਦ Automated Carrier Payments ਨਾਲ ਕੈਰੀਅਰ ਨੂੰ ਭੁਗਤਾਨ। ਵਹੀਕਲ/ਲੋਡ ਮੈਚਿੰਗ ਘੱਟੋ-ਘੱਟ ਵਹੀਕਲ ਕਲਾਸ ਸੁਝਾਉਂਦੀ ਹੈ। ਫੁੱਲ-ਲੋਡ ਫਰੇਟ ਲਈ — ਪਾਰਸਲ ਕੂਰੀਅਰ ਨਹੀਂ। ਲਾਂਚ ਫੋਕਸ: ਮੁੱਖ ਆਸਟ੍ਰੇਲੀਆਈ ਕਾਰੀਡੋਰ (ਸ਼ੁਰੂਆਤ Melbourne–Sydney)। ਹਵਾਲਾ ਪੰਨੇ: /pa/how-it-works ਅਤੇ /pa/faq।',
  },
  {
    id: 'sender-en',
    locale: 'en',
    title: 'For senders / shippers',
    path: '/en/registry',
    tags: ['sender', 'shipper', 'corporate', 'business', 'apply', 'registry', 'benefit'],
    text: 'Senders (corporate shippers) use CLOX to post full-load freight, compare vetted carrier bids, track shipments, and use planned Protected Upfront Payments. Business benefits: clear price comparisons, live GPS tracking (when live), vetted carrier compliance, fewer futile-trip disputes, and better supply-chain control — skip middleman margin and ship more directly. How to apply now: open Pre-launch Registry → choose Sender → submit company legal name, ABN, shipping origin, operational models, bidding preferences, monthly volume, email/phone, and infrastructure acknowledgements. Registration is free interest only — not a binding contract and not live platform access yet. Early registrants may get priority bidding access and fast-tracked onboarding when the marketplace opens. Path: /{locale}/registry?role=sender',
  },
  {
    id: 'sender-hi',
    locale: 'hi',
    title: 'सेंडर / शिपर के लिए',
    path: '/hi/registry',
    tags: ['sender', 'shipper', 'corporate', 'business', 'apply', 'registry', 'benefit'],
    text: 'सेंडर (कॉर्पोरेट शिपर) CLOX पर फुल-लोड फ्रेट पोस्ट करते हैं, जाँचे हुए कैरियर बिड्स की तुलना करते हैं, शिपमेंट ट्रैक करते हैं, और नियोजित Protected Upfront Payments उपयोग करते हैं। व्यापार लाभ: स्पष्ट मूल्य तुलना, लाइव GPS ट्रैकिंग (लाइव होने पर), जाँचा कैरियर अनुपालन, कम विवाद, बेहतर सप्लाई-चेन नियंत्रण। अभी आवेदन: प्री-लॉन्च रजिस्ट्री → Sender चुनें → कंपनी नाम, ABN, शिपिंग ओरिजिन, ऑपरेशनल मॉडल, बिडिंग प्राथमिकताएँ, मासिक वॉल्यूम, ईमेल/फ़ोन जमा करें। यह केवल रुचि है — बाध्यकारी अनुबंध या लाइव एक्सेस नहीं। पाथ: /hi/registry?role=sender',
  },
  {
    id: 'sender-pa',
    locale: 'pa',
    title: 'ਸੈਂਡਰ / ਸ਼ਿਪਰ ਲਈ',
    path: '/pa/registry',
    tags: ['sender', 'shipper', 'corporate', 'business', 'apply', 'registry', 'benefit'],
    text: 'ਸੈਂਡਰ (ਕਾਰਪੋਰੇਟ ਸ਼ਿਪਰ) CLOX ਉੱਤੇ ਫੁੱਲ-ਲੋਡ ਫਰੇਟ ਪੋਸਟ ਕਰਦੇ ਹਨ, ਜਾਂਚੇ ਹੋਏ ਕੈਰੀਅਰ ਬਿਡਾਂ ਦੀ ਤੁਲਨਾ ਕਰਦੇ ਹਨ, ਸ਼ਿਪਮੈਂਟ ਟਰੈਕ ਕਰਦੇ ਹਨ, ਅਤੇ Protected Upfront Payments ਵਰਤਦੇ ਹਨ। ਕਾਰੋਬਾਰ ਲਾਭ: ਸਪਸ਼ਟ ਕੀਮਤ ਤੁਲਨਾ, ਲਾਈਵ GPS ਟਰੈਕਿੰਗ, ਜਾਂਚਿਆ ਕੈਰੀਅਰ ਅਨੁਪਾਲਨ, ਘੱਟ ਵਿਵਾਦ, ਬਿਹਤਰ ਸਪਲਾਈ-ਚੇਨ ਕੰਟਰੋਲ। ਹੁਣ ਅਰਜ਼ੀ: ਪ੍ਰੀ-ਲਾਂਚ ਰਜਿਸਟਰੀ → Sender ਚੁਣੋ → ਕੰਪਨੀ ਨਾਮ, ABN, ਸ਼ਿਪਿੰਗ ਮੂਲ, ਆਪਰੇਸ਼ਨਲ ਮਾਡਲ, ਬਿਡਿੰਗ ਤਰਜੀਹਾਂ, ਮਹੀਨਾਵਾਰ ਵਾਲੀਅਮ, ਈਮੇਲ/ਫ਼ੋਨ ਜਮ੍ਹਾਂ ਕਰੋ। ਇਹ ਸਿਰਫ਼ ਦਿਲਚਸਪੀ ਹੈ — ਬਾਈਡਿੰਗ ਇਕਰਾਰ ਜਾਂ ਲਾਈਵ ਐਕਸੈਸ ਨਹੀਂ। ਪਾਥ: /pa/registry?role=sender',
  },
  {
    id: 'carrier-en',
    locale: 'en',
    title: 'For carriers / transport fleets',
    path: '/en/registry',
    tags: ['carrier', 'fleet', 'transport', 'truck', 'business', 'apply', 'registry', 'benefit'],
    text: 'Carriers (transport fleets / heavy-vehicle operators) use CLOX to bid on matching full-load jobs, unlock idle capacity, and reduce unpaid-freight risk via planned Protected Upfront Payments and Automated Carrier Payments after delivery. Business benefits: protected payments before trips, direct live job boards (Per-KM routes or Hourly blocks with planned 4-hour minimum), direct marketplace access to corporate freight matching vehicle type/location, and verified carrier status. Verification planned: valid ABN, Public Liability evidence (target $10M–$20M), active RWC / vehicle compliance, admin review before live bidding. How to apply now: open Pre-launch Registry → choose Carrier → submit fleet/company name, ABN, depot state, fleet composition, capabilities, compliance authorisation, email/phone. Not live access yet. Path: /{locale}/registry?role=carrier',
  },
  {
    id: 'carrier-hi',
    locale: 'hi',
    title: 'कैरियर / ट्रांसपोर्ट फ़्लीट के लिए',
    path: '/hi/registry',
    tags: ['carrier', 'fleet', 'transport', 'truck', 'business', 'apply', 'registry', 'benefit'],
    text: 'कैरियर (ट्रांसपोर्ट फ़्लीट / हेवी-व्हीकल ऑपरेटर) CLOX पर मैचिंग फुल-लोड जॉब्स पर बिड करते हैं, खाली क्षमता उपयोग करते हैं, और Protected Upfront Payments से अवैतनिक फ्रेट जोखिम कम करते हैं। लाभ: यात्रा से पहले सुरक्षित भुगतान, डायरेक्ट जॉब बोर्ड (Per-KM या Hourly), कॉर्पोरेट फ्रेट तक सीधी पहुँच, वेरिफाइड कैरियर स्टेटस। सत्यापन: ABN, Public Liability, RWC, एडमिन समीक्षा। अभी आवेदन: प्री-लॉन्च रजिस्ट्री → Carrier → फ़्लीट/कंपनी नाम, ABN, डिपो राज्य, फ़्लीट संरचना, क्षमताएँ, अनुपालन अनुमति, ईमेल/फ़ोन। पाथ: /hi/registry?role=carrier',
  },
  {
    id: 'carrier-pa',
    locale: 'pa',
    title: 'ਕੈਰੀਅਰ / ਟਰਾਂਸਪੋਰਟ ਫਲੀਟ ਲਈ',
    path: '/pa/registry',
    tags: ['carrier', 'fleet', 'transport', 'truck', 'business', 'apply', 'registry', 'benefit'],
    text: 'ਕੈਰੀਅਰ (ਟਰਾਂਸਪੋਰਟ ਫਲੀਟ / ਹੈਵੀ-ਵਹੀਕਲ ਆਪਰੇਟਰ) CLOX ਉੱਤੇ ਮੈਚਿੰਗ ਫੁੱਲ-ਲੋਡ ਜੌਬਾਂ ਉੱਤੇ ਬਿਡ ਕਰਦੇ ਹਨ, ਖਾਲੀ ਸਮਰੱਥਾ ਵਰਤਦੇ ਹਨ, ਅਤੇ Protected Upfront Payments ਨਾਲ ਅਦਾਇਗੀ ਜੋਖਮ ਘਟਾਉਂਦੇ ਹਨ। ਲਾਭ: ਯਾਤਰਾ ਤੋਂ ਪਹਿਲਾਂ ਸੁਰੱਖਿਅਤ ਭੁਗਤਾਨ, ਡਾਇਰੈਕਟ ਜੌਬ ਬੋਰਡ, ਕਾਰਪੋਰੇਟ ਫਰੇਟ ਤੱਕ ਸਿੱਧੀ ਪਹੁੰਚ, ਵੈਰੀਫਾਈਡ ਕੈਰੀਅਰ ਸਟੇਟਸ। ਤਸਦੀਕ: ABN, Public Liability, RWC। ਹੁਣ ਅਰਜ਼ੀ: ਪ੍ਰੀ-ਲਾਂਚ ਰਜਿਸਟਰੀ → Carrier → ਫਲੀਟ/ਕੰਪਨੀ ਨਾਮ, ABN, ਡਿਪੋ ਰਾਜ, ਫਲੀਟ ਬਣਤਰ, ਸਮਰੱਥਾਵਾਂ, ਈਮੇਲ/ਫ਼ੋਨ। ਪਾਥ: /pa/registry?role=carrier',
  },
  {
    id: 'eoi-en',
    locale: 'en',
    title: 'Partner EOI — how partners apply',
    path: '/en/partner/eoi',
    tags: ['partner', 'eoi', 'territory', 'business', 'apply', 'benefit', 'bde'],
    text: 'Partner EOI is for Territory Sales Partners / Independent Territory Partners who want to grow CLOX regionally. Partners operate with operational autonomy as independent commercial contractors (not employees) — setting their own hours and strategies. Commercial terms (fees/commissions) are discussed after application under NDA and are not published on the public form. How to apply: open Partner EOI → provide target state/region, suburbs/city, full legal name, company name, ABN, optional ACN, email, phone, corporate address, network experience, execution strategy, and accept the declaration. Selection requires KYB and executive review; submitting EOI is not admission. Path: /{locale}/partner/eoi',
  },
  {
    id: 'eoi-hi',
    locale: 'hi',
    title: 'पार्टनर EOI — आवेदन कैसे करें',
    path: '/hi/partner/eoi',
    tags: ['partner', 'eoi', 'territory', 'business', 'apply', 'benefit', 'bde'],
    text: 'पार्टनर EOI Territory Sales Partner / Independent Territory Partner के लिए है जो क्षेत्रीय रूप से CLOX बढ़ाना चाहते हैं। पार्टनर स्वतंत्र वाणिज्यिक ठेकेदार के रूप में परिचालन स्वायत्तता रखते हैं — कर्मचारी नहीं। वाणिज्यिक शर्तें आवेदन के बाद NDA के अंतर्गत साझा होती हैं। आवेदन: Partner EOI खोलें → लक्ष्य राज्य/क्षेत्र, उपनगर/शहर, कानूनी नाम, कंपनी, ABN, वैकल्पिक ACN, ईमेल, फ़ोन, पता, नेटवर्क अनुभव, निष्पादन रणनीति, घोषणा स्वीकृति। KYB और कार्यकारी समीक्षा आवश्यक; EOI प्रवेश की गारंटी नहीं। पाथ: /hi/partner/eoi',
  },
  {
    id: 'eoi-pa',
    locale: 'pa',
    title: 'ਪਾਰਟਨਰ EOI — ਅਰਜ਼ੀ ਕਿਵੇਂ ਦਿਓ',
    path: '/pa/partner/eoi',
    tags: ['partner', 'eoi', 'territory', 'business', 'apply', 'benefit', 'bde'],
    text: 'ਪਾਰਟਨਰ EOI Territory Sales Partner / Independent Territory Partner ਲਈ ਹੈ ਜੋ ਖੇਤਰੀ ਤੌਰ ਉੱਤੇ CLOX ਵਧਾਉਣਾ ਚਾਹੁੰਦੇ ਹਨ। ਪਾਰਟਨਰ ਆਜ਼ਾਦ ਵਪਾਰਕ ਠੇਕੇਦਾਰ ਵਜੋਂ ਕੰਮ ਕਰਦੇ ਹਨ — ਕਰਮਚਾਰੀ ਨਹੀਂ। ਵਪਾਰਕ ਸ਼ਰਤਾਂ ਅਰਜ਼ੀ ਤੋਂ ਬਾਅਦ NDA ਅਧੀਨ ਸਾਂਝੀਆਂ ਹੁੰਦੀਆਂ ਹਨ। ਅਰਜ਼ੀ: Partner EOI ਖੋਲ੍ਹੋ → ਟਾਰਗੇਟ ਰਾਜ/ਖੇਤਰ, ਉਪਨਗਰ/ਸ਼ਹਿਰ, ਕਾਨੂੰਨੀ ਨਾਮ, ਕੰਪਨੀ, ABN, ਵਿਕਲਪਿਕ ACN, ਈਮੇਲ, ਫ਼ੋਨ, ਪਤਾ, ਨੈਟਵਰਕ ਤਜਰਬਾ, ਐਗਜ਼ੀਕਿਊਸ਼ਨ ਰਣਨੀਤੀ, ਘੋਸ਼ਣਾ। KYB ਅਤੇ ਐਗਜ਼ੀਕਿਊਟਿਵ ਸਮੀਖਿਆ ਲੋੜੀਂਦੀ; EOI ਦਾਖਲੇ ਦੀ ਗਾਰੰਟੀ ਨਹੀਂ। ਪਾਥ: /pa/partner/eoi',
  },
  {
    id: 'apply-en',
    locale: 'en',
    title: 'How to apply / which form',
    path: '/en',
    tags: ['apply', 'register', 'join', 'form', 'which', 'start'],
    text: 'Choose the right form: (1) Corporate sender/shipper → Pre-launch Registry as Sender (/en/registry?role=sender). (2) Carrier/transport fleet → Pre-launch Registry as Carrier (/en/registry?role=carrier). (3) Territory / Independent Territory Partner → Partner EOI (/en/partner/eoi). Pre-launch signup is an expression of interest only — not a binding service contract and not live marketplace access. Have ABN ready (and for carriers: insurance and RWC details when onboarding later). Questions: info@clox.com.au.',
  },
  {
    id: 'apply-hi',
    locale: 'hi',
    title: 'आवेदन कैसे करें / कौन सा फ़ॉर्म',
    path: '/hi',
    tags: ['apply', 'register', 'join', 'form', 'which', 'start'],
    text: 'सही फ़ॉर्म चुनें: (1) कॉर्पोरेट सेंडर/शिपर → रजिस्ट्री में Sender (/hi/registry?role=sender)। (2) कैरियर/ट्रांसपोर्ट फ़्लीट → रजिस्ट्री में Carrier (/hi/registry?role=carrier)। (3) Territory पार्टनर → Partner EOI (/hi/partner/eoi)। प्री-लॉन्च साइनअप केवल रुचि है — बाध्यकारी अनुबंध या लाइव एक्सेस नहीं। ABN तैयार रखें। प्रश्न: info@clox.com.au।',
  },
  {
    id: 'apply-pa',
    locale: 'pa',
    title: 'ਅਰਜ਼ੀ ਕਿਵੇਂ ਦਿਓ / ਕਿਹੜਾ ਫਾਰਮ',
    path: '/pa',
    tags: ['apply', 'register', 'join', 'form', 'which', 'start'],
    text: 'ਸਹੀ ਫਾਰਮ ਚੁਣੋ: (1) ਕਾਰਪੋਰੇਟ ਸੈਂਡਰ/ਸ਼ਿਪਰ → ਰਜਿਸਟਰੀ ਵਿੱਚ Sender (/pa/registry?role=sender)। (2) ਕੈਰੀਅਰ/ਟਰਾਂਸਪੋਰਟ ਫਲੀਟ → ਰਜਿਸਟਰੀ ਵਿੱਚ Carrier (/pa/registry?role=carrier)। (3) Territory ਪਾਰਟਨਰ → Partner EOI (/pa/partner/eoi)। ਪ੍ਰੀ-ਲਾਂਚ ਸਾਈਨਅੱਪ ਸਿਰਫ਼ ਦਿਲਚਸਪੀ ਹੈ — ਬਾਈਡਿੰਗ ਇਕਰਾਰ ਜਾਂ ਲਾਈਵ ਐਕਸੈਸ ਨਹੀਂ। ABN ਤਿਆਰ ਰੱਖੋ। ਸਵਾਲ: info@clox.com.au।',
  },
  {
    id: 'registry-en',
    locale: 'en',
    title: 'Pre-launch registry details',
    path: '/en/registry',
    tags: ['registry', 'sender', 'carrier', 'shipper', 'transport'],
    text: 'The Pre-launch registry wizard captures company or fleet details, ABN, contact email/phone, operational preferences, and infrastructure acknowledgements (easyAML, Protected Upfront Payments via Stripe Connect, Monoova NPP PayTo). Submitting does not grant platform access yet. Early cohort benefits (promotional, subject to launch agreements): priority live-bidding access, zero initiation fees, fast-tracked onboarding, and complimentary fleet management SaaS tools when available.',
  },
  {
    id: 'registry-hi',
    locale: 'hi',
    title: 'प्री-लॉन्च रजिस्ट्री विवरण',
    path: '/hi/registry',
    tags: ['registry', 'sender', 'carrier'],
    text: 'प्री-लॉन्च रजिस्ट्री विज़ार्ड कंपनी/फ़्लीट विवरण, ABN, संपर्क, ऑपरेशनल प्राथमिकताएँ और इन्फ़्रास्ट्रक्चर स्वीकृतियाँ (easyAML, Stripe Connect, Monoova) एकत्र करता है। जमा करने से प्लेटफ़ॉर्म एक्सेस नहीं मिलता।',
  },
  {
    id: 'registry-pa',
    locale: 'pa',
    title: 'ਪ੍ਰੀ-ਲਾਂਚ ਰਜਿਸਟਰੀ ਵੇਰਵੇ',
    path: '/pa/registry',
    tags: ['registry', 'sender', 'carrier'],
    text: 'ਪ੍ਰੀ-ਲਾਂਚ ਰਜਿਸਟਰੀ ਵਿਜ਼ਾਰਡ ਕੰਪਨੀ/ਫਲੀਟ ਵੇਰਵੇ, ABN, ਸੰਪਰਕ, ਆਪਰੇਸ਼ਨਲ ਤਰਜੀਹਾਂ ਅਤੇ ਇੰਫਰਾਸਟਰਕਚਰ ਸਵੀਕ੍ਰਿਤੀਆਂ (easyAML, Stripe Connect, Monoova) ਇਕੱਠੀਆਂ ਕਰਦਾ ਹੈ। ਜਮ੍ਹਾਂ ਕਰਨ ਨਾਲ ਪਲੇਟਫਾਰਮ ਐਕਸੈਸ ਨਹੀਂ ਮਿਲਦਾ।',
  },
  {
    id: 'investors-en',
    locale: 'en',
    title: 'Investor portal',
    path: '/en/investors',
    tags: ['investor', 'equity', 'capital', 'accreditation'],
    public: false,
    text: 'The Investor portal is an early-access equity round registration and pre-qualification form. Classifications include sophisticated investor, professional investor, and strategic industry partner. Capital bands start at AUD 25,000. Information is protected under NDA-style acknowledgements and used only for accreditation review. Questions: info@clox.com.au.',
  },
  {
    id: 'investors-hi',
    locale: 'hi',
    title: 'इन्वेस्टर पोर्टल',
    path: '/hi/investors',
    tags: ['investor', 'equity', 'capital'],
    public: false,
    text: 'इन्वेस्टर पोर्टल अर्ली-एक्सेस इक्विटी राउंड के लिए प्री-क्वालीफ़िकेशन फ़ॉर्म है। वर्ग: परिष्कृत, पेशेवर और रणनीतिक उद्योग पार्टनर। पूंजी बैंड AUD 25,000 से शुरू होते हैं। प्रश्न: info@clox.com.au।',
  },
  {
    id: 'investors-pa',
    locale: 'pa',
    title: 'ਨਿਵੇਸ਼ਕ ਪੋਰਟਲ',
    path: '/pa/investors',
    tags: ['investor', 'equity', 'capital'],
    public: false,
    text: 'ਨਿਵੇਸ਼ਕ ਪੋਰਟਲ ਅਰਲੀ-ਐਕਸੈਸ ਇਕਵਿਟੀ ਰਾਊਂਡ ਲਈ ਪ੍ਰੀ-ਕੁਆਲੀਫਿਕੇਸ਼ਨ ਫਾਰਮ ਹੈ। ਵਰਗ: ਸੋਫਿਸਟੀਕੇਟਡ, ਪੇਸ਼ੇਵਰ ਅਤੇ ਰਣਨੀਤਕ ਉਦਯੋਗ ਪਾਰਟਨਰ। ਪੂੰਜੀ ਬੈਂਡ AUD 25,000 ਤੋਂ ਸ਼ੁਰੂ ਹੁੰਦੇ ਹਨ। ਸਵਾਲ: info@clox.com.au।',
  },
  {
    id: 'privacy-en',
    locale: 'en',
    title: 'Privacy',
    path: '/en/privacy',
    tags: ['privacy', 'legal', 'data'],
    text: 'Achieve Global Enterprises Pty Ltd (ABN 48 626 269 387) trading as CLOX Freight Forwarding collects pre-launch personal and corporate data under the Australian Privacy Principles / Privacy Act 1988 (Cth). Data may include identity/contact details, ABN/ACN and fleet info, technical usage data, and communications. Uses: early-access waitlist, ABN pre-validation, consented marketing, Shipper/Carrier segmentation, Territory Sales Partner / Independent Territory Partner applications, and site improvement. Data is stored on AU-jurisdiction servers with encryption in transit and at rest. Not sold; may be shared with hosting/CRM providers, ABR checks, or as required by law. Full KYC/KYB (easyAML/Trulioo) only at official onboarding. Rights: access, correction, opt-out. Contact: info@clox.com.au · 18 Solferino Rd, Clyde North, VIC 3978.',
  },
  {
    id: 'privacy-hi',
    locale: 'hi',
    title: 'गोपनीयता',
    path: '/hi/privacy',
    tags: ['privacy', 'legal', 'data'],
    text: 'Achieve Global Enterprises Pty Ltd (ABN 48 626 269 387) ट्रेडिंग नाम CLOX Freight Forwarding Privacy Act 1988 (Cth) / APPs के अंतर्गत प्री-लॉन्च व्यक्तिगत और कॉर्पोरेट डेटा एकत्र करता है। उपयोग: वेटलिस्ट, ABN पूर्व-सत्यापन, सहमति के साथ मार्केटिंग, शिपर/कैरियर विभाजन, Territory Sales Partner / Independent Territory Partner आवेदन। डेटा ऑस्ट्रेलियाई अधिकार क्षेत्र के सर्वरों पर एन्क्रिप्शन के साथ संग्रहीत। नहीं बेचा जाता। अधिकार: पहुँच, सुधार, ऑप्ट-आउट। संपर्क: info@clox.com.au · 18 Solferino Rd, Clyde North, VIC 3978.',
  },
  {
    id: 'privacy-pa',
    locale: 'pa',
    title: 'ਪਰਾਈਵੇਸੀ',
    path: '/pa/privacy',
    tags: ['privacy', 'legal', 'data'],
    text: 'Achieve Global Enterprises Pty Ltd (ABN 48 626 269 387) ਟ੍ਰੇਡਿੰਗ ਨਾਮ CLOX Freight Forwarding Privacy Act 1988 (Cth) / APPs ਅਧੀਨ ਪ੍ਰੀ-ਲਾਂਚ ਨਿੱਜੀ ਅਤੇ ਕਾਰਪੋਰੇਟ ਡੇਟਾ ਇਕੱਠਾ ਕਰਦਾ ਹੈ। ਵਰਤੋਂ: ਵੇਟਲਿਸਟ, ABN ਪੂਰਵ-ਤਸਦੀਕ, ਸਹਿਮਤੀ ਨਾਲ ਮਾਰਕੀਟਿੰਗ, ਸ਼ਿਪਰ/ਕੈਰੀਅਰ ਵੰਡ, Territory Sales Partner / Independent Territory Partner ਅਰਜ਼ੀਆਂ। ਡੇਟਾ ਆਸਟ੍ਰੇਲੀਆਈ ਅਧਿਕਾਰ ਖੇਤਰ ਦੇ ਸਰਵਰਾਂ ਉੱਤੇ ਇਨਕ੍ਰਿਪਸ਼ਨ ਨਾਲ ਸੰਭਾਲਿਆ ਜਾਂਦਾ ਹੈ। ਨਹੀਂ ਵੇਚਿਆ ਜਾਂਦਾ। ਅਧਿਕਾਰ: ਪਹੁੰਚ, ਸੁਧਾਰ, ਆਪਟ-ਆਉਟ। ਸੰਪਰਕ: info@clox.com.au · 18 Solferino Rd, Clyde North, VIC 3978.',
  },
  {
    id: 'terms-en',
    locale: 'en',
    title: 'Terms',
    path: '/en/terms',
    tags: ['terms', 'legal'],
    text: 'CLOX pre-launch website Terms & Conditions are operated by Achieve Global Enterprises Pty Ltd trading as CLOX Freight Forwarding (ABN 48 626 269 387), Victoria, Australia. Registration/EOI/mailing list signup is not a binding service contract. Early-access incentives are promotional and subject to formal Shipper/Carrier agreements at launch. Provide accurate ABN/ACN information. Site IP belongs to Achieve Global Enterprises. No scraping, false submissions, or unauthorized access. Third-party links (Stripe, Monoova, easyAML) are informational only. Content is as-is; roadmap features may change. Liability limited under ACL. Indemnity for misuse. Victorian law and exclusive jurisdiction. Pre-launch Terms will be superseded by Master Terms, Carrier Agreement, and Shipper Agreement at go-live. Contact: info@clox.com.au.',
  },
  {
    id: 'terms-hi',
    locale: 'hi',
    title: 'शर्तें',
    path: '/hi/terms',
    tags: ['terms', 'legal'],
    text: 'CLOX प्री-लॉन्च वेबसाइट नियम Achieve Global Enterprises Pty Ltd (ट्रेडिंग नाम CLOX Freight Forwarding, ABN 48 626 269 387), विक्टोरिया द्वारा संचालित हैं। पंजीकरण/EOI बाध्यकारी सेवा अनुबंध नहीं है। प्रोत्साहन प्रचारक हैं और लॉन्च पर औपचारिक समझौतों के अधीन। सटीक ABN/ACN दें। IP Achieve Global की है। स्क्रैपिंग/गलत जानकारी/अनधिकृत पहुँच निषिद्ध। सामग्री जैसा-है; रोडमैप बदल सकता है। ACL के अंतर्गत दायित्व सीमित। विक्टोरिया कानून। संपर्क: info@clox.com.au।',
  },
  {
    id: 'terms-pa',
    locale: 'pa',
    title: 'ਸ਼ਰਤਾਂ',
    path: '/pa/terms',
    tags: ['terms', 'legal'],
    text: 'CLOX ਪ੍ਰੀ-ਲਾਂਚ ਵੈੱਬਸਾਈਟ ਨਿਯਮ Achieve Global Enterprises Pty Ltd (ਟ੍ਰੇਡਿੰਗ ਨਾਮ CLOX Freight Forwarding, ABN 48 626 269 387), ਵਿਕਟੋਰੀਆ ਵੱਲੋਂ ਸੰਚਾਲਿਤ ਹਨ। ਰਜਿਸਟਰੇਸ਼ਨ/EOI ਬਾਧਿਆਕਾਰੀ ਸੇਵਾ ਇਕਰਾਰਨਾਮਾ ਨਹੀਂ। ਪ੍ਰੋਤਸਾਹਨ ਪ੍ਰਚਾਰਕ ਹਨ ਅਤੇ ਲਾਂਚ ਉੱਤੇ ਰਸਮੀ ਇਕਰਾਰਨਾਮਿਆਂ ਅਧੀਨ। ਸਹੀ ABN/ACN ਦਿਓ। IP Achieve Global ਦੀ ਹੈ। ਸਕ੍ਰੈਪਿੰਗ/ਗਲਤ ਜਾਣਕਾਰੀ/ਅਣਅਧਿਕਾਰਤ ਪਹੁੰਚ ਮਨਾਹੀ। ਸਮੱਗਰੀ ਜਿਵੇਂ-ਹੈ; ਰੋਡਮੈਪ ਬਦਲ ਸਕਦਾ ਹੈ। ACL ਅਧੀਨ ਦਾਇਤਵ ਸੀਮਿਤ। ਵਿਕਟੋਰੀਆ ਕਾਨੂੰਨ। ਸੰਪਰਕ: info@clox.com.au।',
  },
  {
    id: 'boundaries-both',
    locale: 'both',
    title: 'Assistant boundaries',
    path: '/en',
    tags: ['assistant', 'limits', 'safety'],
    text: 'The CLOX site guide helps users understand what CLOX is, how it works, business benefits for senders/carriers/partners, and how to apply via Registry or Partner EOI. It answers ONLY from approved CLOX site content. It must refuse off-topic requests. It must not invent live pricing, ETAs, matching results, legal advice, or investment advice. It must not collect or submit personal lead details. When unsure, direct the user to the correct form page.',
  },
];
