-- M6 jobs marketplace fields

ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "title" TEXT;
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "pickupAt" TIMESTAMP(3);
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "deadWeightKg" DOUBLE PRECISION;
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "lengthCm" DOUBLE PRECISION;
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "widthCm" DOUBLE PRECISION;
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "heightCm" DOUBLE PRECISION;
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "chargeableWeightKg" DOUBLE PRECISION;
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "loadTypes" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "requiresDg" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "requiresReefer" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "requiresOversize" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "minVehicleClass" TEXT;
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "recommendedVehicleClass" TEXT;
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "siteManeuverability" TEXT;
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "siteFacility" TEXT;
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "siteDisclaimerAcceptedAt" TIMESTAMP(3);
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "hourlyPattern" TEXT;
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "routeDistanceKm" DOUBLE PRECISION;
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "routeDurationMinutes" DOUBLE PRECISION;
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "routeFatigueBreakMinutes" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "billableHours" DOUBLE PRECISION;

ALTER TABLE "JobStop" ADD COLUMN IF NOT EXISTS "receiverName" TEXT;
ALTER TABLE "JobStop" ADD COLUMN IF NOT EXISTS "receiverEmail" TEXT;

ALTER TABLE "Proposal" ADD COLUMN IF NOT EXISTS "vehicleId" TEXT;
ALTER TABLE "Proposal" ADD COLUMN IF NOT EXISTS "driverId" TEXT;
ALTER TABLE "Proposal" ADD COLUMN IF NOT EXISTS "etaMinutes" INTEGER;

CREATE INDEX IF NOT EXISTS "Proposal_vehicleId_idx" ON "Proposal"("vehicleId");
CREATE INDEX IF NOT EXISTS "Proposal_driverId_idx" ON "Proposal"("driverId");

DO $$ BEGIN
  ALTER TABLE "Proposal" ADD CONSTRAINT "Proposal_vehicleId_fkey"
    FOREIGN KEY ("vehicleId") REFERENCES "Vehicle"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "Proposal" ADD CONSTRAINT "Proposal_driverId_fkey"
    FOREIGN KEY ("driverId") REFERENCES "Driver"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
